// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8N9sWMoL_MhhfdoGosBBJWN5zjxkeeXo',
    appId: '1:198828794237:web:4a9bde5c18613b1222ec14',
    messagingSenderId: '198828794237',
    projectId: 'prjkasir-da860',
    authDomain: 'prjkasir-da860.firebaseapp.com',
    databaseURL: 'https://prjkasir-da860-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'prjkasir-da860.firebasestorage.app',
    measurementId: 'G-Y0P3XWQYTR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyG4PIqm53j6nRhl8wBLxGOZkx1T_5Xcs',
    appId: '1:198828794237:android:5786de775fefa53922ec14',
    messagingSenderId: '198828794237',
    projectId: 'prjkasir-da860',
    databaseURL: 'https://prjkasir-da860-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'prjkasir-da860.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEfu0r7S5g5EaLedMPYU3DtOGcLDtaUD8',
    appId: '1:198828794237:ios:23746f26a94ed8c222ec14',
    messagingSenderId: '198828794237',
    projectId: 'prjkasir-da860',
    databaseURL: 'https://prjkasir-da860-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'prjkasir-da860.firebasestorage.app',
    iosBundleId: 'com.intihose.appPos',
  );
}
